setwd("C:/Users/chofi/Documents/2019/Maestria/Programming_Geostatistic/GIT/Packages/MB2")
install.packages("MB2")
library(MB2)
hello_eagles(c("Sofi"))
install.packages("lubridate")
library(lubridate)
Sys.time()             

## devtools::install_github("sofigdl/MB2")
library(mme2)


install.packages("Rcpp")
library(Rcpp)
library(devtools)
library(roxygen2)
library(usethis)
library(lubridate)
devtools::install_github("DLauJim/mme2")
devtools::install_github("sofigdl/MB2")
library(mme2)
library(MB2)
hello_eagles("Sofi")
remove.packages("mme2")
